### ISSUE TITLE
Combine dynamic with static BrightcovePlayerSDK

### ISSUE THREAD

**Issue by MendyGini-Apps** [brightcove/brightcove-player-sdk-ios-googlecast#2]
I need to implement in my application [brightcove-player-sdk-ios-googlecast](https://github.com/brightcove/brightcove-player-sdk-ios-googlecast) and [brightcove-player-sdk-ios-ima](https://github.com/brightcove/brightcove-player-sdk-ios-ima) frameworks. the problem is that the `googlecast` framework depends on the `BrightcovePlayerSDK` **_static_** framework and that the `ima` framework depends on `BrightcovePlayerSDK` **_dynamic_**. So I try to combine these two frameworks but there is a conflict. is there a possibility of combining these two frameworks, `brightcove-player-sdk-ios-googlecast` and `brightcove-player-sdk-ios-ima`?

**Comment by timothyrodgers** [comment]
Hi. In the future, please post your relevant questions to the Brightcove Native Player SDKs developer forum at https://groups.google.com/forum/#!forum/brightcove-native-player-sdks.

When using CocoaPods to build your app, the Google Cast SDK is available only as a static framework and iMA is available only as a dynamic framework. Instead of using CocoaPods, you will need to manually integrate the frameworks into your app and instructions for doing so are available in the various framework documents.

The Brightcove Google Cast plugin does not provide any support for casting ads. You might need to implement your own Google Cast interface which can be done directly in your app.

Good luck and please post any future questions to the [developer forum](https://groups.google.com/forum/#!forum/brightcove-native-player-sdks).
